version: '3.8'

services:
  backend:
    build: ./uat_tool
    ports:
      - "8005:8005"
    volumes:
      - ./uat_tool:/app
      - sqlite_data:/var/lib/sqlite
    environment:
      - DEBUG=1
      - DATABASE_URL=sqlite:////var/lib/sqlite/db.sqlite3
      - PYTHONPATH=/app
      - PATH=/opt/venv/bin:$PATH
    restart: unless-stopped

  frontend:
    build: ./uat-frontend
    ports:
      - "5100:5100"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - frontend
      - backend

volumes:
  sqlite_data:
