# Generated by Django 5.1.7 on 2025-03-27 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='functionality',
            field=models.ForeignKey(blank=True, help_text='The functionality this test case belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='uat.functionality'),
        ),
    ]
