# Generated by Django 5.1.7 on 2025-03-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststep',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='test_step_attachments/'),
        ),
    ]
