# Generated by Django 5.1.7 on 2025-04-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionality',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='The sort order of the functionality within the system.'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='The sort order of the test case.'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='The sort order of the execution.'),
        ),
        migrations.AddField(
            model_name='teststep',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='The sort order of the step within the test case.'),
        ),
    ]
