# Generated by Django 5.1.7 on 2025-03-13 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uat', '0002_testexecution_completed_at_testexecution_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defect',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uat.customuser'),
        ),
    ]
