# Generated by Django 5.1.7 on 2025-04-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uat', '0002_functionality_sort_order_testcase_sort_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teststep',
            name='sort_order',
        ),
    ]
