# Generated by Django 5.1.7 on 2025-03-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uat', '0003_remove_teststep_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststep',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='test_step_attachments/'),
        ),
    ]
