# Generated by Django 5.1.7 on 2025-04-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uat', '0003_remove_teststep_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststep',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='The sort order of the step within the test case.'),
        ),
    ]
