# Generated by Django 5.1.7 on 2025-03-20 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uat', '0004_teststep_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_test_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
