# Generated by Django 5.1.7 on 2025-03-20 21:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uat', '0005_testcase_assigned_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defect',
            options={'ordering': ['-created_at'], 'verbose_name': 'Defect', 'verbose_name_plural': 'Defects'},
        ),
        migrations.AddField(
            model_name='defect',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Notes on how the defect was resolved.', null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the defect was last updated.'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time when the test case was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready_for_testing', 'Ready for Testing'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', help_text='The status of the test case.', max_length=20),
        ),
        migrations.AlterField(
            model_name='defect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the defect was created.'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='description',
            field=models.TextField(help_text='A detailed description of the defect, including steps to reproduce.'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='execution',
            field=models.ForeignKey(help_text='The test execution during which this defect was identified.', on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='uat.testexecution'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='reported_by',
            field=models.ForeignKey(help_text='The user who reported this defect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_defects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='defect',
            name='resolved',
            field=models.BooleanField(default=False, help_text='Indicates whether the defect has been resolved.'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='The severity level of the defect.', max_length=10),
        ),
        migrations.AlterField(
            model_name='defect',
            name='title',
            field=models.CharField(help_text='A brief title summarizing the defect.', max_length=255),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of the functionality.', null=True),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='name',
            field=models.CharField(help_text='The name of the functionality.', max_length=255),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='system',
            field=models.ForeignKey(help_text='The system the functionality belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='functionalities', to='uat.system'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the organization was created.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of the organization.', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='The name of the organization.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of the system.', null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(help_text='The name of the system.', max_length=255),
        ),
        migrations.AlterField(
            model_name='system',
            name='organization',
            field=models.ForeignKey(help_text='The organization the system belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='uat.organization'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text='The user assigned to this test case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_test_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='created_by',
            field=models.ForeignKey(help_text='The user who created this test case.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='description',
            field=models.TextField(help_text='A detailed description of the test case.'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_result',
            field=models.TextField(help_text='The expected result of the test case.'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='functionality',
            field=models.ForeignKey(help_text='The functionality this test case belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='uat.functionality'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='title',
            field=models.CharField(help_text='The title of the test case.', max_length=255),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='The date and time when the execution was completed.', null=True),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the execution.', null=True),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the execution started.'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed'), ('blocked', 'Blocked')], help_text='The status of the test execution.', max_length=20),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='test_case',
            field=models.ForeignKey(help_text='The test case being executed.', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='uat.testcase'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='tester',
            field=models.ForeignKey(help_text='The user executing the test case.', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='attachment',
            field=models.FileField(blank=True, help_text='An optional attachment for the step.', null=True, upload_to='test_step_attachments/'),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='description',
            field=models.TextField(help_text='A detailed description of the step.'),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='expected_result',
            field=models.TextField(help_text='The expected result of the step.'),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='step_number',
            field=models.PositiveIntegerField(help_text='The step number in the test case.'),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='test_case',
            field=models.ForeignKey(help_text='The test case this step belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='uat.testcase'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the user was created.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text="The user's first name.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the user is active.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indicates whether the user is a staff member.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text="The date and time of the user's last login.", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(help_text='The organization the user belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='uat.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, help_text='The OTP secret for two-factor authentication.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('tester', 'Tester'), ('viewer', 'Viewer')], default='tester', help_text='The role of the user.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(help_text="The user's WhatsApp number.", max_length=15, unique=True),
        ),
    ]
