# Generated by Django 5.1.7 on 2025-03-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uat', '0006_alter_defect_options_defect_resolution_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
    ]
