# Generated by Django 5.1.7 on 2025-03-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uat', '0007_defect_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='attachment',
            field=models.FileField(blank=True, help_text='An optional attachment for the step.', null=True, upload_to='defects_attachments/'),
        ),
    ]
