# Generated by Django 5.1.7 on 2025-03-25 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uat', '0008_defect_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, help_text='The organization the user belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='uat.organization'),
        ),
    ]
