# Generated by Django 5.1.7 on 2025-03-27 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uat', '0010_remove_user_organization_userorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(help_text='The organization the user belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='uat.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('tester', 'Tester'), ('viewer', 'Viewer')], default='admin', help_text='The role of the user.', max_length=20),
        ),
    ]
